// IMPORTANT: DO NOT REMOVE THIS FILE
//
// This file is auto-generated by ember-cli-dfinity. It must always be present
// in the root directory of the build EmberJS app, or else the webpack will
// not generate a valid dapp.
